# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Metropolis sampler using Rcpp
#' @description A Metropolis sampler using Rcpp
#' @param sigma vector of standard deviations.
#' @param x0 initial value.
#' @param N  the length of the chain.
#' @return a random sample of size
#' @export
MetropolisC <- function(sigma, x0, N) {
    .Call('_StatComp20073_MetropolisC', PACKAGE = 'StatComp20073', sigma, x0, N)
}

#' @title A Rayleigh sampler using Rcpp
#' @description A Rayleigh sampler using Rcpp
#' @param sigma parameter of rayleigh density
#' @param n size of Rayleigh random number
#' @return a Rayleigh random sample
#' @export
RayleighC <- function(n, sigma) {
    .Call('_StatComp20073_RayleighC', PACKAGE = 'StatComp20073', n, sigma)
}

